name: Maven Delpoy robocode api

on: [push,pull_request,pull_request_target]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: cd robocode-sources/robocode && sh mvnw install
      - name: Deploy with maven
        run: cd robocode-sources/robocode && sh mvnw deploy -Dregistry=https://maven.pkg.github.com/it-economics -Dtoken=$GH_TOKEN
